//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeStyleAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeStyleAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should be prefixed with &apos;_&apos;..
        /// </summary>
        internal static string FieldNameInstanceFieldDescripition {
            get {
                return ResourceManager.GetString("FieldNameInstanceFieldDescripition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not prefixed with &apos;_&apos;.
        /// </summary>
        internal static string FieldNameInstanceFieldMessageFormat {
            get {
                return ResourceManager.GetString("FieldNameInstanceFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not prefixed with &apos;_&apos;.
        /// </summary>
        internal static string FieldNameInstanceFieldTitle {
            get {
                return ResourceManager.GetString("FieldNameInstanceFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should be prefixed with &apos;s_&apos;..
        /// </summary>
        internal static string FieldNameStaticFieldDescripition {
            get {
                return ResourceManager.GetString("FieldNameStaticFieldDescripition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not prefixed with &apos;s_&apos;.
        /// </summary>
        internal static string FieldNameStaticFieldMessageFormat {
            get {
                return ResourceManager.GetString("FieldNameStaticFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not prefixed with &apos;s_&apos;.
        /// </summary>
        internal static string FieldNameStaticFieldTitle {
            get {
                return ResourceManager.GetString("FieldNameStaticFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should be prefixed with &apos;t_&apos;..
        /// </summary>
        internal static string FieldNameThreadStaticFieldDescripition {
            get {
                return ResourceManager.GetString("FieldNameThreadStaticFieldDescripition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not prefixed with &apos;t_&apos;.
        /// </summary>
        internal static string FieldNameThreadStaticFieldMessageFormat {
            get {
                return ResourceManager.GetString("FieldNameThreadStaticFieldMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not prefixed with &apos;t_&apos;.
        /// </summary>
        internal static string FieldNameThreadStaticFieldTitle {
            get {
                return ResourceManager.GetString("FieldNameThreadStaticFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace imports should be specified at the top of the file, outside of namespace declarations.
        /// </summary>
        internal static string NamespacePositionDescripition {
            get {
                return ResourceManager.GetString("NamespacePositionDescripition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace imports should be specified at the top of the file, outside of namespace declarations.
        /// </summary>
        internal static string NamespacePositionMessageFormat {
            get {
                return ResourceManager.GetString("NamespacePositionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace imports should be specified at the top of the file, outside of namespace declarations.
        /// </summary>
        internal static string NamespacePositionTitle {
            get {
                return ResourceManager.GetString("NamespacePositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be specified..
        /// </summary>
        internal static string VisibilityModifierDescription {
            get {
                return ResourceManager.GetString("VisibilityModifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be specified..
        /// </summary>
        internal static string VisibilityModifierMessageFormat {
            get {
                return ResourceManager.GetString("VisibilityModifierMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be the first modifier..
        /// </summary>
        internal static string VisibilityModifierPositionDescription {
            get {
                return ResourceManager.GetString("VisibilityModifierPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be the first modifier..
        /// </summary>
        internal static string VisibilityModifierPositionMessageFormat {
            get {
                return ResourceManager.GetString("VisibilityModifierPositionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be the first modifier..
        /// </summary>
        internal static string VisibilityModifierPositionTitle {
            get {
                return ResourceManager.GetString("VisibilityModifierPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility modifier should be specified..
        /// </summary>
        internal static string VisibilityModifierTitle {
            get {
                return ResourceManager.GetString("VisibilityModifierTitle", resourceCulture);
            }
        }
    }
}
